# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aed8712ee29aae98409d81c5f389de2dc7d912664e6c404c3c68daf7e1d255b9da22bc1365e250bb46b52693cb4c9da60ff37262b8a47a27e94857eff12d8a14

test:
  secret_key_base: af2a0ce9d4b9675f62ecfad4c954ebae24bcbfcb30db3a38fa10611901d6c4c6e1917509f83b36f1889baa3de54a28d08ea03082daf9a55f5b2544ccc73b4964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
